name: Tests

on:
  push:
    branches: [ main, develop,  dev/* ]

  pull_request:
    branches: [ main, develop, dev/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE: 14.x

jobs:
  run:
    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test
